### ISSUE TITLE
Error popup styling

### ISSUE THREAD

**Issue by johnmal-dev** [Code-Conjurers/Voting-Booth#21]
The styling for the modal popups is noticeably different from the web page. Is it possible to style the popups similarly to the poll cards?
<img width="596" alt="Screenshot 2023-02-21 at 12 23 33 PM" src="https://user-images.githubusercontent.com/56036354/220416182-c23be133-6ef1-464d-85ab-3c71c508a58b.png">

**Comment by nobrayn** [comment]
Thanks for the feedback!
