### ISSUE TITLE
inconsistent pointers on button hovers

### ISSUE THREAD

**Issue by johnmal-dev** [Code-Conjurers/Voting-Booth#23]
The hover pointers are different for the 'Submit' and 'Find A Poll' button. 

This also occurs after poll creation with 'View Your Poll' and 'Copy Poll Link' buttons

https://user-images.githubusercontent.com/56036354/220417904-1d9af64c-be41-4532-9dd1-47bb16335a04.mov

**Comment by fionafreemark** [comment]
Fixed! Thanks John
