### ISSUE TITLE
Error-handling double-check

### ISSUE THREAD

**Issue by graydonj** [Code-Conjurers/Voting-Booth#26]
![Screenshot_20230221_125126](https://user-images.githubusercontent.com/116847252/220422137-a24c4255-ac1c-4f4f-88fa-9eb33e22451a.png)
From PollCreation.js Component... This is great backup error-handling, but it would also be good to have the input form fields have a "required" in the JSX as well. This means you only get the Sweet Alert pop-up if the user manages to bypass the front-end error handling, but both could be useful.

**Comment by nobrayn** [comment]
Thanks!
